// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ8K8OvSm-aC-hrmyuDNICGDmALDixZiE',
    appId: '1:551677593171:web:62e9eb2ff3747495dc28a6',
    messagingSenderId: '551677593171',
    projectId: 'flutterproject-f281c',
    authDomain: 'flutterproject-f281c.firebaseapp.com',
    storageBucket: 'flutterproject-f281c.firebasestorage.app',
    measurementId: 'G-62QG01BEVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPMeNI9xLEJue4G6OlFWisJe2nlhzIVP0',
    appId: '1:551677593171:android:c6506e28be79972ddc28a6',
    messagingSenderId: '551677593171',
    projectId: 'flutterproject-f281c',
    storageBucket: 'flutterproject-f281c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH9TGVLv9gqMN5PGmvMxFJsdJ83sHBwRQ',
    appId: '1:551677593171:ios:38f3c03545e0c89adc28a6',
    messagingSenderId: '551677593171',
    projectId: 'flutterproject-f281c',
    storageBucket: 'flutterproject-f281c.firebasestorage.app',
    iosBundleId: 'com.example.flutterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH9TGVLv9gqMN5PGmvMxFJsdJ83sHBwRQ',
    appId: '1:551677593171:ios:38f3c03545e0c89adc28a6',
    messagingSenderId: '551677593171',
    projectId: 'flutterproject-f281c',
    storageBucket: 'flutterproject-f281c.firebasestorage.app',
    iosBundleId: 'com.example.flutterproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ8K8OvSm-aC-hrmyuDNICGDmALDixZiE',
    appId: '1:551677593171:web:5772f55f1e62a23adc28a6',
    messagingSenderId: '551677593171',
    projectId: 'flutterproject-f281c',
    authDomain: 'flutterproject-f281c.firebaseapp.com',
    storageBucket: 'flutterproject-f281c.firebasestorage.app',
    measurementId: 'G-C12G6PLBLG',
  );
}
